<form action="<?= $block->getUrlBuilder()->getUrl('ahtcustomer/user/create') ?>" method="get">
    <div>
        First name: <input type="text" name="firstName" placeholder="First name">
    </div>
    <div>
        Last name: <input type="text" name="lastName" placeholder="Last name">
    </div>
    <div>
        Email: <input type="email" name="email" placeholder="Email">
    </div>
    <div>
        Password: <input type="password" name="password" placeholder="Password">
    </div>
    <div>
        Gender:
        <select name="gender">
            <option value="1">Male</option>
            <option value="2">Female</option>
        </select>
    </div>
    <div>
        <input type="submit" name="createbtn" value="Submit">
    </div>
</form>