<?php
$customer = $block->getCustomer();
?>
<form action="<?= $block->getUrlBuilder()->getUrl('ahtcustomer/user/edit', ['id' => $customer->getId()]) ?>" method="get">
    <div>
        First name: <input type="text" name="firstName" placeholder="First name" value="<?= $customer->getFirstname() ?>">
    </div>
    <div>
        Last name: <input type="text" name="lastName" placeholder="Last name" value="<?= $customer->getLastname() ?>">
    </div>
    <div>
        Email: <input type="email" name="email" placeholder="Email" value="<?= $customer->getEmail() ?>" disabled>
    </div>
    <div>
        Password: <input type="password" name="password" placeholder="Password">
    </div>
    <div>
        Gender:
        <select name="gender">
            <option value="1" <?php if ($customer->getGender() == 1) { echo 'selected'; } ?>>Male</option>
            <option value="2" <?php if ($customer->getGender() == 2) { echo 'selected'; } ?>>Female</option>
        </select>
    </div>
    <div>
        <input type="submit" name="editbtn" value="Submit">
    </div>
</form>